module Test.LambdaBuffers.Runtime.PlutusTx.PlutusTx (
  dayCompiled,
  integerCompiled,
  boolCompiled,
  workDayCompiled,
  freeDayCompiled,
  fooACompiled,
  fooBCompiled,
  fooCCompiled,
  fooDCompiled,
  -- fooECompiled, -- Compiling this causes an OOM
  maybeCompiled,
  eitherCompiled,
  listCompiled,
  addressCompiled,
  assetClassCompiled,
  currencySymbolCompiled,
  credentialCompiled,
  mapCompiled,
  intervalCompiled,
  extendedCompiled,
  lowerBoundCompiled,
  datumCompiled,
  datumHashCompiled,
  ledgerBytesCompiled,
  posixTimeCompiled,
  posixTimeRangeCompiled,
  plutusDataCompiled,
  redeemerCompiled,
  redeemerHashCompiled,
  scriptHashCompiled,
  stakingCredentialCompiled,
  tokenNameCompiled,
  txIdCompiled,
  txOutRefCompiled,
  upperBoundCompiled,
  valueCompiled,
  dcertCompiled,
  txInInfoCompiled,
  txOutCompiled,
  scriptPurposeCompiled,
  txInfoCompiled,
  scriptContextCompiled,
  outputDatumCompiled,
  txInInfo2Compiled,
  txOut2Compiled,
  txInfo2Compiled,
  scriptContext2Compiled,
  rationalCompiled,
  txIdV3Compiled,
  txOutRefV3Compiled,
  coldCommitteeCredentialV3Compiled,
  hotCommitteeCredentialV3Compiled,
  drepCredentialV3Compiled,
  drepV3Compiled,
  delegateeV3Compiled,
  txCertV3Compiled,
  voterV3Compiled,
  voteV3Compiled,
  governanceActionIdV3Compiled,
  committeeV3Compiled,
  constitutionV3Compiled,
  protocolVersionV3Compiled,
  changedParametersV3Compiled,
  governanceActionV3Compiled,
  proposalProcedureV3Compiled,
  scriptPurposeV3Compiled,
  scriptInfoV3Compiled,
  txInInfoV3Compiled,
  txInfoV3Compiled,
  scriptContextV3Compiled,
)
where

import Test.LambdaBuffers.Runtime.PlutusTx.PlutusTx.Prelude (boolCompiled, dayCompiled, eitherCompiled, fooACompiled, fooBCompiled, fooCCompiled, fooDCompiled, freeDayCompiled, integerCompiled, listCompiled, maybeCompiled, rationalCompiled, workDayCompiled)
import Test.LambdaBuffers.Runtime.PlutusTx.PlutusTx.V1 (addressCompiled, assetClassCompiled, credentialCompiled, currencySymbolCompiled, datumCompiled, datumHashCompiled, extendedCompiled, intervalCompiled, ledgerBytesCompiled, lowerBoundCompiled, mapCompiled, plutusDataCompiled, posixTimeCompiled, posixTimeRangeCompiled, redeemerCompiled, redeemerHashCompiled, scriptHashCompiled, stakingCredentialCompiled, tokenNameCompiled, txIdCompiled, txOutRefCompiled, upperBoundCompiled, valueCompiled)
import Test.LambdaBuffers.Runtime.PlutusTx.PlutusTx.V1Tx (dcertCompiled, scriptContextCompiled, scriptPurposeCompiled, txInInfoCompiled, txInfoCompiled, txOutCompiled)
import Test.LambdaBuffers.Runtime.PlutusTx.PlutusTx.V2 (outputDatumCompiled, scriptContext2Compiled, txInInfo2Compiled, txInfo2Compiled, txOut2Compiled)
import Test.LambdaBuffers.Runtime.PlutusTx.PlutusTx.V3 (changedParametersV3Compiled, coldCommitteeCredentialV3Compiled, committeeV3Compiled, constitutionV3Compiled, delegateeV3Compiled, drepCredentialV3Compiled, drepV3Compiled, governanceActionIdV3Compiled, governanceActionV3Compiled, hotCommitteeCredentialV3Compiled, proposalProcedureV3Compiled, protocolVersionV3Compiled, txCertV3Compiled, txIdV3Compiled, txOutRefV3Compiled, voteV3Compiled, voterV3Compiled)
import Test.LambdaBuffers.Runtime.PlutusTx.PlutusTx.V3Tx (scriptContextV3Compiled, scriptInfoV3Compiled, scriptPurposeV3Compiled, txInInfoV3Compiled, txInfoV3Compiled)
