//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: repls/lambdabuffers-source.proto

package lambdabuffers.source;

@kotlin.jvm.JvmSynthetic
public inline fun localTypeRef(block: lambdabuffers.source.LocalTypeRefKt.Dsl.() -> kotlin.Unit): lambdabuffers.source.LambdabuffersSource.LocalTypeRef =
  lambdabuffers.source.LocalTypeRefKt.Dsl._create(lambdabuffers.source.LambdabuffersSource.LocalTypeRef.newBuilder()).apply { block() }._build()
public object LocalTypeRefKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: lambdabuffers.source.LambdabuffersSource.LocalTypeRef.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: lambdabuffers.source.LambdabuffersSource.LocalTypeRef.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): lambdabuffers.source.LambdabuffersSource.LocalTypeRef = _builder.build()

    /**
     * <code>.lambdabuffers.source.TypeConName type_con_name = 1;</code>
     */
    public var typeConName: lambdabuffers.source.LambdabuffersSource.TypeConName
      @JvmName("getTypeConName")
      get() = _builder.getTypeConName()
      @JvmName("setTypeConName")
      set(value) {
        _builder.setTypeConName(value)
      }
    /**
     * <code>.lambdabuffers.source.TypeConName type_con_name = 1;</code>
     */
    public fun clearTypeConName() {
      _builder.clearTypeConName()
    }
    /**
     * <code>.lambdabuffers.source.TypeConName type_con_name = 1;</code>
     * @return Whether the typeConName field is set.
     */
    public fun hasTypeConName(): kotlin.Boolean {
      return _builder.hasTypeConName()
    }

    /**
     * <code>.lambdabuffers.source.SourceInfo source_info = 2;</code>
     */
    public var sourceInfo: lambdabuffers.source.LambdabuffersSource.SourceInfo
      @JvmName("getSourceInfo")
      get() = _builder.getSourceInfo()
      @JvmName("setSourceInfo")
      set(value) {
        _builder.setSourceInfo(value)
      }
    /**
     * <code>.lambdabuffers.source.SourceInfo source_info = 2;</code>
     */
    public fun clearSourceInfo() {
      _builder.clearSourceInfo()
    }
    /**
     * <code>.lambdabuffers.source.SourceInfo source_info = 2;</code>
     * @return Whether the sourceInfo field is set.
     */
    public fun hasSourceInfo(): kotlin.Boolean {
      return _builder.hasSourceInfo()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun lambdabuffers.source.LambdabuffersSource.LocalTypeRef.copy(block: lambdabuffers.source.LocalTypeRefKt.Dsl.() -> kotlin.Unit): lambdabuffers.source.LambdabuffersSource.LocalTypeRef =
  lambdabuffers.source.LocalTypeRefKt.Dsl._create(this.toBuilder()).apply { block() }._build()
