//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: repls/lambdabuffers-source.proto

package lambdabuffers.source;

@kotlin.jvm.JvmSynthetic
public inline fun typeBody(block: lambdabuffers.source.TypeBodyKt.Dsl.() -> kotlin.Unit): lambdabuffers.source.LambdabuffersSource.TypeBody =
  lambdabuffers.source.TypeBodyKt.Dsl._create(lambdabuffers.source.LambdabuffersSource.TypeBody.newBuilder()).apply { block() }._build()
public object TypeBodyKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: lambdabuffers.source.LambdabuffersSource.TypeBody.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: lambdabuffers.source.LambdabuffersSource.TypeBody.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): lambdabuffers.source.LambdabuffersSource.TypeBody = _builder.build()
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun lambdabuffers.source.LambdabuffersSource.TypeBody.copy(block: lambdabuffers.source.TypeBodyKt.Dsl.() -> kotlin.Unit): lambdabuffers.source.LambdabuffersSource.TypeBody =
  lambdabuffers.source.TypeBodyKt.Dsl._create(this.toBuilder()).apply { block() }._build()
