//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: repls/lambdabuffers-source.proto

package lambdabuffers.source;

@kotlin.jvm.JvmSynthetic
public inline fun typeDefinition(block: lambdabuffers.source.TypeDefinitionKt.Dsl.() -> kotlin.Unit): lambdabuffers.source.LambdabuffersSource.TypeDefinition =
  lambdabuffers.source.TypeDefinitionKt.Dsl._create(lambdabuffers.source.LambdabuffersSource.TypeDefinition.newBuilder()).apply { block() }._build()
public object TypeDefinitionKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  public class Dsl private constructor(
    private val _builder: lambdabuffers.source.LambdabuffersSource.TypeDefinition.Builder
  ) {
    public companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: lambdabuffers.source.LambdabuffersSource.TypeDefinition.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): lambdabuffers.source.LambdabuffersSource.TypeDefinition = _builder.build()

    /**
     * <code>.lambdabuffers.source.TypeConName type_name = 1;</code>
     */
    public var typeName: lambdabuffers.source.LambdabuffersSource.TypeConName
      @JvmName("getTypeName")
      get() = _builder.getTypeName()
      @JvmName("setTypeName")
      set(value) {
        _builder.setTypeName(value)
      }
    /**
     * <code>.lambdabuffers.source.TypeConName type_name = 1;</code>
     */
    public fun clearTypeName() {
      _builder.clearTypeName()
    }
    /**
     * <code>.lambdabuffers.source.TypeConName type_name = 1;</code>
     * @return Whether the typeName field is set.
     */
    public fun hasTypeName(): kotlin.Boolean {
      return _builder.hasTypeName()
    }

    /**
     * <code>.lambdabuffers.source.Kind type_kind = 2;</code>
     */
    public var typeKind: lambdabuffers.source.LambdabuffersSource.Kind
      @JvmName("getTypeKind")
      get() = _builder.getTypeKind()
      @JvmName("setTypeKind")
      set(value) {
        _builder.setTypeKind(value)
      }
    /**
     * <code>.lambdabuffers.source.Kind type_kind = 2;</code>
     */
    public fun clearTypeKind() {
      _builder.clearTypeKind()
    }
    /**
     * <code>.lambdabuffers.source.Kind type_kind = 2;</code>
     * @return Whether the typeKind field is set.
     */
    public fun hasTypeKind(): kotlin.Boolean {
      return _builder.hasTypeKind()
    }

    /**
     * <code>.lambdabuffers.source.TypeBody type_body = 3;</code>
     */
    public var typeBody: lambdabuffers.source.LambdabuffersSource.TypeBody
      @JvmName("getTypeBody")
      get() = _builder.getTypeBody()
      @JvmName("setTypeBody")
      set(value) {
        _builder.setTypeBody(value)
      }
    /**
     * <code>.lambdabuffers.source.TypeBody type_body = 3;</code>
     */
    public fun clearTypeBody() {
      _builder.clearTypeBody()
    }
    /**
     * <code>.lambdabuffers.source.TypeBody type_body = 3;</code>
     * @return Whether the typeBody field is set.
     */
    public fun hasTypeBody(): kotlin.Boolean {
      return _builder.hasTypeBody()
    }

    /**
     * <code>.lambdabuffers.source.SourceInfo source_info = 4;</code>
     */
    public var sourceInfo: lambdabuffers.source.LambdabuffersSource.SourceInfo
      @JvmName("getSourceInfo")
      get() = _builder.getSourceInfo()
      @JvmName("setSourceInfo")
      set(value) {
        _builder.setSourceInfo(value)
      }
    /**
     * <code>.lambdabuffers.source.SourceInfo source_info = 4;</code>
     */
    public fun clearSourceInfo() {
      _builder.clearSourceInfo()
    }
    /**
     * <code>.lambdabuffers.source.SourceInfo source_info = 4;</code>
     * @return Whether the sourceInfo field is set.
     */
    public fun hasSourceInfo(): kotlin.Boolean {
      return _builder.hasSourceInfo()
    }
  }
}
@kotlin.jvm.JvmSynthetic
public inline fun lambdabuffers.source.LambdabuffersSource.TypeDefinition.copy(block: lambdabuffers.source.TypeDefinitionKt.Dsl.() -> kotlin.Unit): lambdabuffers.source.LambdabuffersSource.TypeDefinition =
  lambdabuffers.source.TypeDefinitionKt.Dsl._create(this.toBuilder()).apply { block() }._build()
