[package]
name = "lbt-plutus"
version = "0.1.0"
edition = "2021"

[dependencies]
plutus-ledger-api = { path = ".extras/plutus-ledger-api-0.2.0" }
lbf-plutus-rust-golden-api = { path = ".extras/lbf-plutus-rust-golden-api-0.1.0" }
lbf-prelude = { path = ".extras/lbf-prelude-0.1.0" }
lbr-prelude = { path = ".extras/lbr-prelude-0.1.0", features = ["plutus"] }
serde_json = "1.0.108"
num-bigint = "0.4.4"
