[package]
name = "lbt-prelude"
version = "0.1.0"
edition = "2021"

[dependencies]
lbf-plutus-rust-golden-api = { path = ".extras/lbf-plutus-rust-golden-api" }
lbf-prelude = { path = ".extras/lbf-prelude" }
lbr-prelude = { path = ".extras/lbr-prelude" }
serde_json = "1.0.108"
num-bigint = "0.4.4"
plutus-ledger-api = { git = "https://github.com/mlabs-haskell/plutus-ledger-api-rust", features = [
  "lbf",
], rev = "c9e09c867decdcb6e405b1231dad447436c820c5" }
