[package]
name = "lbt-plutus"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
plutus-ledger-api = { path = ".extras/plutus-ledger-api-3", features = ["lbf"] }
lbf-plutus-golden-api = { path = ".extras/lbf-plutus-golden-api-0.1.0" }
lbf-prelude = { path = ".extras/lbf-prelude-0.1.0" }
lbr-prelude = { path = ".extras/lbr-prelude-v0" }
serde_json = "1.0.108"
num-bigint = "0.4.4"
pretty_assertions = "1.4.1"
