[package]
name = "lbt-prelude"
version = "0.1.0"
edition = "2021"

[dependencies]
lbf-plutus-rust-golden-api = { path = ".extras/lbf-plutus-rust-golden-api" }
lbf-prelude = { path = ".extras/lbf-prelude" }
serde_json = "1.0.108"
num-bigint = "0.4.4"
plutus-ledger-api = { git = "https://github.com/mlabs-haskell/plutus-ledger-api-rust", features = [
  "lbf",
], rev = "fb93fa590908580eb40368369bf6614d42ce9a95" }
