[package]
name = "lbt-prelude"
version = "0.1.0"
edition = "2021"

[dependencies]
lbf-prelude-golden-api = { path = ".extras/lbf-prelude-golden-api-0.1.0" }
lbf-prelude = { path = ".extras/lbf-prelude-0.1.0" }
lbr-prelude = { version = "0.1.3" }
serde_json = "1.0.108"
num-bigint = "0.4.4"
