-- \| A short example demonstrating how one can use the types and instances
-- generated by the PlutusTx backend.

import LambdaBuffers.Example.PlutusTx (Emoji (Emoji'ThumbsDown, Emoji'ThumbsUp))
import PlutusTx.Eq qualified

main :: IO ()
main = do
  print $ Emoji'ThumbsUp PlutusTx.Eq.== Emoji'ThumbsDown

  print $ Emoji'ThumbsUp PlutusTx.Eq.== Emoji'ThumbsUp
