modules {
  module_name {
    parts {
      name: "A"
      source_info {
        file: "good/A.lbf"
        pos_from { column: 8 row: 1 }
        pos_to { column: 9 row: 1 }
      }
    }
    source_info {
      file: "good/A.lbf"
      pos_from { column: 8 row: 1 }
      pos_to { column: 9 row: 1 }
    }
  }
  type_defs {
    ty_name {
      name: "A"
      source_info {
        file: "good/A.lbf"
        pos_from { column: 5 row: 3 }
        pos_to { column: 6 row: 3 }
      }
    }
    ty_abs {
      ty_body {
        sum {
          constructors {
            constr_name {
              name: "MkA"
              source_info {
                file: "good/A.lbf"
                pos_from { column: 9 row: 3 }
                pos_to { column: 12 row: 3 }
              }
            }
            product {
              ntuple {
                source_info {
                  file: "good/A.lbf"
                  pos_from { column: 12 row: 3 }
                  pos_to { column: 12 row: 3 }
                }
              }
            }
          }
          source_info {
            file: "good/A.lbf"
            pos_from { column: 9 row: 3 }
            pos_to { column: 12 row: 3 }
          }
        }
      }
    }
    source_info {
      file: "good/A.lbf"
      pos_from { column: 1 row: 3 }
      pos_to { column: 12 row: 3 }
    }
  }
  source_info {
    file: "good/A.lbf"
    pos_from { column: 1 row: 1 }
    pos_to { column: 12 row: 3 }
  }
}
modules {
  module_name {
    parts {
      name: "A"
      source_info {
        file: "good/A/B.lbf"
        pos_from { column: 8 row: 1 }
        pos_to { column: 9 row: 1 }
      }
    }
    parts {
      name: "B"
      source_info {
        file: "good/A/B.lbf"
        pos_from { column: 10 row: 1 }
        pos_to { column: 11 row: 1 }
      }
    }
    source_info {
      file: "good/A/B.lbf"
      pos_from { column: 8 row: 1 }
      pos_to { column: 11 row: 1 }
    }
  }
  type_defs {
    ty_name {
      name: "A"
      source_info {
        file: "good/A/B.lbf"
        pos_from { column: 5 row: 3 }
        pos_to { column: 6 row: 3 }
      }
    }
    ty_abs {
      ty_body {
        sum {
          constructors {
            constr_name {
              name: "MkA"
              source_info {
                file: "good/A/B.lbf"
                pos_from { column: 9 row: 3 }
                pos_to { column: 12 row: 3 }
              }
            }
            product {
              ntuple {
                source_info {
                  file: "good/A/B.lbf"
                  pos_from { column: 12 row: 3 }
                  pos_to { column: 12 row: 3 }
                }
              }
            }
          }
          source_info {
            file: "good/A/B.lbf"
            pos_from { column: 9 row: 3 }
            pos_to { column: 12 row: 3 }
          }
        }
      }
    }
    source_info {
      file: "good/A/B.lbf"
      pos_from { column: 1 row: 3 }
      pos_to { column: 12 row: 3 }
    }
  }
  source_info {
    file: "good/A/B.lbf"
    pos_from { column: 1 row: 1 }
    pos_to { column: 12 row: 3 }
  }
}
modules {
  module_name {
    parts {
      name: "B"
      source_info {
        file: "good/B.lbf"
        pos_from { column: 8 row: 1 }
        pos_to { column: 9 row: 1 }
      }
    }
    source_info {
      file: "good/B.lbf"
      pos_from { column: 8 row: 1 }
      pos_to { column: 9 row: 1 }
    }
  }
  type_defs {
    ty_name {
      name: "A"
      source_info {
        file: "good/B.lbf"
        pos_from { column: 5 row: 3 }
        pos_to { column: 6 row: 3 }
      }
    }
    ty_abs {
      ty_body {
        sum {
          constructors {
            constr_name {
              name: "MkA"
              source_info {
                file: "good/B.lbf"
                pos_from { column: 9 row: 3 }
                pos_to { column: 12 row: 3 }
              }
            }
            product {
              ntuple {
                source_info {
                  file: "good/B.lbf"
                  pos_from { column: 12 row: 3 }
                  pos_to { column: 12 row: 3 }
                }
              }
            }
          }
          source_info {
            file: "good/B.lbf"
            pos_from { column: 9 row: 3 }
            pos_to { column: 12 row: 3 }
          }
        }
      }
    }
    source_info {
      file: "good/B.lbf"
      pos_from { column: 1 row: 3 }
      pos_to { column: 12 row: 3 }
    }
  }
  source_info {
    file: "good/B.lbf"
    pos_from { column: 1 row: 1 }
    pos_to { column: 12 row: 3 }
  }
}
modules {
  module_name {
    parts {
      name: "C"
      source_info {
        file: "good/C.lbf"
        pos_from { column: 8 row: 1 }
        pos_to { column: 9 row: 1 }
      }
    }
    source_info {
      file: "good/C.lbf"
      pos_from { column: 8 row: 1 }
      pos_to { column: 9 row: 1 }
    }
  }
  type_defs {
    ty_name {
      name: "A"
      source_info {
        file: "good/C.lbf"
        pos_from { column: 5 row: 3 }
        pos_to { column: 6 row: 3 }
      }
    }
    ty_abs {
      ty_body {
        sum {
          constructors {
            constr_name {
              name: "MkA"
              source_info {
                file: "good/C.lbf"
                pos_from { column: 9 row: 3 }
                pos_to { column: 12 row: 3 }
              }
            }
            product {
              ntuple {
                source_info {
                  file: "good/C.lbf"
                  pos_from { column: 12 row: 3 }
                  pos_to { column: 12 row: 3 }
                }
              }
            }
          }
          source_info {
            file: "good/C.lbf"
            pos_from { column: 9 row: 3 }
            pos_to { column: 12 row: 3 }
          }
        }
      }
    }
    source_info {
      file: "good/C.lbf"
      pos_from { column: 1 row: 3 }
      pos_to { column: 12 row: 3 }
    }
  }
  source_info {
    file: "good/C.lbf"
    pos_from { column: 1 row: 1 }
    pos_to { column: 12 row: 3 }
  }
}
modules {
  module_name {
    parts {
      name: "Test"
      source_info {
        file: "good/Test.lbf"
        pos_from { column: 8 row: 1 }
        pos_to { column: 12 row: 1 }
      }
    }
    source_info {
      file: "good/Test.lbf"
      pos_from { column: 8 row: 1 }
      pos_to { column: 12 row: 1 }
    }
  }
  type_defs {
    ty_name {
      name: "Maybe"
      source_info {
        file: "good/Test.lbf"
        pos_from { column: 5 row: 14 }
        pos_to { column: 10 row: 14 }
      }
    }
    ty_abs {
      ty_args {
        arg_name { name: "a" }
        arg_kind { kind_ref: KIND_REF_TYPE }
        source_info {
          file: "good/Test.lbf"
          pos_from { column: 11 row: 14 }
          pos_to { column: 12 row: 14 }
        }
      }
      ty_body {
        sum {
          constructors {
            constr_name {
              name: "Just"
              source_info {
                file: "good/Test.lbf"
                pos_from { column: 15 row: 14 }
                pos_to { column: 19 row: 14 }
              }
            }
            product {
              ntuple {
                fields {
                  ty_var {
                    var_name {
                      name: "a"
                      source_info {
                        file: "good/Test.lbf"
                        pos_from { column: 20 row: 14 }
                        pos_to { column: 21 row: 14 }
                      }
                    }
                    source_info {
                      file: "good/Test.lbf"
                      pos_from { column: 20 row: 14 }
                      pos_to { column: 21 row: 14 }
                    }
                  }
                }
                source_info {
                  file: "good/Test.lbf"
                  pos_from { column: 20 row: 14 }
                  pos_to { column: 22 row: 14 }
                }
              }
            }
          }
          constructors {
            constr_name {
              name: "Nothing"
              source_info {
                file: "good/Test.lbf"
                pos_from { column: 24 row: 14 }
                pos_to { column: 31 row: 14 }
              }
            }
            product {
              ntuple {
                source_info {
                  file: "good/Test.lbf"
                  pos_from { column: 31 row: 14 }
                  pos_to { column: 31 row: 14 }
                }
              }
            }
          }
          source_info {
            file: "good/Test.lbf"
            pos_from { column: 15 row: 14 }
            pos_to { column: 31 row: 14 }
          }
        }
      }
    }
    source_info {
      file: "good/Test.lbf"
      pos_from { column: 1 row: 14 }
      pos_to { column: 31 row: 14 }
    }
  }
  type_defs {
    ty_name {
      name: "Either"
      source_info {
        file: "good/Test.lbf"
        pos_from { column: 5 row: 16 }
        pos_to { column: 11 row: 16 }
      }
    }
    ty_abs {
      ty_args {
        arg_name { name: "a" }
        arg_kind { kind_ref: KIND_REF_TYPE }
        source_info {
          file: "good/Test.lbf"
          pos_from { column: 12 row: 16 }
          pos_to { column: 13 row: 16 }
        }
      }
      ty_args {
        arg_name { name: "b" }
        arg_kind { kind_ref: KIND_REF_TYPE }
        source_info {
          file: "good/Test.lbf"
          pos_from { column: 14 row: 16 }
          pos_to { column: 15 row: 16 }
        }
      }
      ty_body {
        sum {
          constructors {
            constr_name {
              name: "Left"
              source_info {
                file: "good/Test.lbf"
                pos_from { column: 18 row: 16 }
                pos_to { column: 22 row: 16 }
              }
            }
            product {
              ntuple {
                fields {
                  ty_var {
                    var_name {
                      name: "a"
                      source_info {
                        file: "good/Test.lbf"
                        pos_from { column: 23 row: 16 }
                        pos_to { column: 24 row: 16 }
                      }
                    }
                    source_info {
                      file: "good/Test.lbf"
                      pos_from { column: 23 row: 16 }
                      pos_to { column: 24 row: 16 }
                    }
                  }
                }
                source_info {
                  file: "good/Test.lbf"
                  pos_from { column: 23 row: 16 }
                  pos_to { column: 25 row: 16 }
                }
              }
            }
          }
          constructors {
            constr_name {
              name: "Right"
              source_info {
                file: "good/Test.lbf"
                pos_from { column: 27 row: 16 }
                pos_to { column: 32 row: 16 }
              }
            }
            product {
              ntuple {
                fields {
                  ty_var {
                    var_name {
                      name: "b"
                      source_info {
                        file: "good/Test.lbf"
                        pos_from { column: 33 row: 16 }
                        pos_to { column: 34 row: 16 }
                      }
                    }
                    source_info {
                      file: "good/Test.lbf"
                      pos_from { column: 33 row: 16 }
                      pos_to { column: 34 row: 16 }
                    }
                  }
                }
                source_info {
                  file: "good/Test.lbf"
                  pos_from { column: 33 row: 16 }
                  pos_to { column: 34 row: 16 }
                }
              }
            }
          }
          source_info {
            file: "good/Test.lbf"
            pos_from { column: 18 row: 16 }
            pos_to { column: 34 row: 16 }
          }
        }
      }
    }
    source_info {
      file: "good/Test.lbf"
      pos_from { column: 1 row: 16 }
      pos_to { column: 34 row: 16 }
    }
  }
  type_defs {
    ty_name {
      name: "List"
      source_info {
        file: "good/Test.lbf"
        pos_from { column: 5 row: 18 }
        pos_to { column: 9 row: 18 }
      }
    }
    ty_abs {
      ty_args {
        arg_name { name: "a" }
        arg_kind { kind_ref: KIND_REF_TYPE }
        source_info {
          file: "good/Test.lbf"
          pos_from { column: 10 row: 18 }
          pos_to { column: 11 row: 18 }
        }
      }
      ty_body {
        sum {
          constructors {
            constr_name {
              name: "Nil"
              source_info {
                file: "good/Test.lbf"
                pos_from { column: 14 row: 18 }
                pos_to { column: 17 row: 18 }
              }
            }
            product {
              ntuple {
                source_info {
                  file: "good/Test.lbf"
                  pos_from { column: 18 row: 18 }
                  pos_to { column: 18 row: 18 }
                }
              }
            }
          }
          constructors {
            constr_name {
              name: "List"
              source_info {
                file: "good/Test.lbf"
                pos_from { column: 20 row: 18 }
                pos_to { column: 24 row: 18 }
              }
            }
            product {
              ntuple {
                fields {
                  ty_var {
                    var_name {
                      name: "a"
                      source_info {
                        file: "good/Test.lbf"
                        pos_from { column: 25 row: 18 }
                        pos_to { column: 26 row: 18 }
                      }
                    }
                    source_info {
                      file: "good/Test.lbf"
                      pos_from { column: 25 row: 18 }
                      pos_to { column: 26 row: 18 }
                    }
                  }
                }
                fields {
                  ty_app {
                    ty_func {
                      ty_ref {
                        local_ty_ref {
                          ty_name {
                            name: "List"
                            source_info {
                              file: "good/Test.lbf"
                              pos_from { column: 28 row: 18 }
                              pos_to { column: 32 row: 18 }
                            }
                          }
                          source_info {
                            file: "good/Test.lbf"
                            pos_from { column: 28 row: 18 }
                            pos_to { column: 32 row: 18 }
                          }
                        }
                      }
                    }
                    ty_args {
                      ty_var {
                        var_name {
                          name: "a"
                          source_info {
                            file: "good/Test.lbf"
                            pos_from { column: 33 row: 18 }
                            pos_to { column: 34 row: 18 }
                          }
                        }
                        source_info {
                          file: "good/Test.lbf"
                          pos_from { column: 33 row: 18 }
                          pos_to { column: 34 row: 18 }
                        }
                      }
                    }
                    source_info {
                      file: "good/Test.lbf"
                      pos_from { column: 34 row: 18 }
                      pos_to { column: 34 row: 18 }
                    }
                  }
                }
                source_info {
                  file: "good/Test.lbf"
                  pos_from { column: 25 row: 18 }
                  pos_to { column: 35 row: 18 }
                }
              }
            }
          }
          source_info {
            file: "good/Test.lbf"
            pos_from { column: 14 row: 18 }
            pos_to { column: 35 row: 18 }
          }
        }
      }
    }
    source_info {
      file: "good/Test.lbf"
      pos_from { column: 1 row: 18 }
      pos_to { column: 35 row: 18 }
    }
  }
  type_defs {
    ty_name {
      name: "Int"
      source_info {
        file: "good/Test.lbf"
        pos_from { column: 8 row: 20 }
        pos_to { column: 11 row: 20 }
      }
    }
    ty_abs { ty_body { opaque {} } }
    source_info {
      file: "good/Test.lbf"
      pos_from { column: 1 row: 20 }
      pos_to { column: 11 row: 20 }
    }
  }
  type_defs {
    ty_name {
      name: "Foo"
      source_info {
        file: "good/Test.lbf"
        pos_from { column: 5 row: 22 }
        pos_to { column: 8 row: 22 }
      }
    }
    ty_abs {
      ty_args {
        arg_name { name: "a" }
        arg_kind { kind_ref: KIND_REF_TYPE }
        source_info {
          file: "good/Test.lbf"
          pos_from { column: 9 row: 22 }
          pos_to { column: 10 row: 22 }
        }
      }
      ty_body {
        sum {
          constructors {
            constr_name {
              name: "MkFoo"
              source_info {
                file: "good/Test.lbf"
                pos_from { column: 13 row: 22 }
                pos_to { column: 18 row: 22 }
              }
            }
            product {
              ntuple {
                fields {
                  ty_ref {
                    foreign_ty_ref {
                      ty_name {
                        name: "A"
                        source_info {
                          file: "good/Test.lbf"
                          pos_from { column: 5 row: 23 }
                          pos_to { column: 6 row: 23 }
                        }
                      }
                      module_name {
                        parts {
                          name: "A"
                          source_info {
                            file: "good/Test.lbf"
                            pos_from { column: 8 row: 3 }
                            pos_to { column: 9 row: 3 }
                          }
                        }
                        source_info {
                          file: "good/Test.lbf"
                          pos_from { column: 8 row: 3 }
                          pos_to { column: 9 row: 3 }
                        }
                      }
                      source_info {
                        file: "good/Test.lbf"
                        pos_from { column: 5 row: 23 }
                        pos_to { column: 6 row: 23 }
                      }
                    }
                  }
                }
                fields {
                  ty_ref {
                    foreign_ty_ref {
                      ty_name {
                        name: "A"
                        source_info {
                          file: "good/Test.lbf"
                          pos_from { column: 7 row: 24 }
                          pos_to { column: 8 row: 24 }
                        }
                      }
                      module_name {
                        parts {
                          name: "A"
                          source_info {
                            file: "good/Test.lbf"
                            pos_from { column: 8 row: 3 }
                            pos_to { column: 9 row: 3 }
                          }
                        }
                        source_info {
                          file: "good/Test.lbf"
                          pos_from { column: 8 row: 3 }
                          pos_to { column: 9 row: 3 }
                        }
                      }
                      source_info {
                        file: "good/Test.lbf"
                        pos_from { column: 5 row: 24 }
                        pos_to { column: 8 row: 24 }
                      }
                    }
                  }
                }
                fields {
                  ty_ref {
                    foreign_ty_ref {
                      ty_name {
                        name: "A"
                        source_info {
                          file: "good/Test.lbf"
                          pos_from { column: 7 row: 25 }
                          pos_to { column: 8 row: 25 }
                        }
                      }
                      module_name {
                        parts {
                          name: "B"
                          source_info {
                            file: "good/Test.lbf"
                            pos_from { column: 18 row: 5 }
                            pos_to { column: 19 row: 5 }
                          }
                        }
                        source_info {
                          file: "good/Test.lbf"
                          pos_from { column: 18 row: 5 }
                          pos_to { column: 19 row: 5 }
                        }
                      }
                      source_info {
                        file: "good/Test.lbf"
                        pos_from { column: 5 row: 25 }
                        pos_to { column: 8 row: 25 }
                      }
                    }
                  }
                }
                fields {
                  ty_ref {
                    foreign_ty_ref {
                      ty_name {
                        name: "A"
                        source_info {
                          file: "good/Test.lbf"
                          pos_from { column: 9 row: 26 }
                          pos_to { column: 10 row: 26 }
                        }
                      }
                      module_name {
                        parts {
                          name: "A"
                          source_info {
                            file: "good/Test.lbf"
                            pos_from { column: 18 row: 7 }
                            pos_to { column: 19 row: 7 }
                          }
                        }
                        parts {
                          name: "B"
                          source_info {
                            file: "good/Test.lbf"
                            pos_from { column: 20 row: 7 }
                            pos_to { column: 21 row: 7 }
                          }
                        }
                        source_info {
                          file: "good/Test.lbf"
                          pos_from { column: 18 row: 7 }
                          pos_to { column: 21 row: 7 }
                        }
                      }
                      source_info {
                        file: "good/Test.lbf"
                        pos_from { column: 5 row: 26 }
                        pos_to { column: 10 row: 26 }
                      }
                    }
                  }
                }
                fields {
                  ty_ref {
                    foreign_ty_ref {
                      ty_name {
                        name: "A"
                        source_info {
                          file: "good/Test.lbf"
                          pos_from { column: 8 row: 27 }
                          pos_to { column: 9 row: 27 }
                        }
                      }
                      module_name {
                        parts {
                          name: "A"
                          source_info {
                            file: "good/Test.lbf"
                            pos_from { column: 18 row: 8 }
                            pos_to { column: 19 row: 8 }
                          }
                        }
                        parts {
                          name: "B"
                          source_info {
                            file: "good/Test.lbf"
                            pos_from { column: 20 row: 8 }
                            pos_to { column: 21 row: 8 }
                          }
                        }
                        source_info {
                          file: "good/Test.lbf"
                          pos_from { column: 18 row: 8 }
                          pos_to { column: 21 row: 8 }
                        }
                      }
                      source_info {
                        file: "good/Test.lbf"
                        pos_from { column: 5 row: 27 }
                        pos_to { column: 9 row: 27 }
                      }
                    }
                  }
                }
                fields {
                  ty_ref {
                    foreign_ty_ref {
                      ty_name {
                        name: "A"
                        source_info {
                          file: "good/Test.lbf"
                          pos_from { column: 7 row: 28 }
                          pos_to { column: 8 row: 28 }
                        }
                      }
                      module_name {
                        parts {
                          name: "C"
                          source_info {
                            file: "good/Test.lbf"
                            pos_from { column: 18 row: 10 }
                            pos_to { column: 19 row: 10 }
                          }
                        }
                        source_info {
                          file: "good/Test.lbf"
                          pos_from { column: 18 row: 10 }
                          pos_to { column: 19 row: 10 }
                        }
                      }
                      source_info {
                        file: "good/Test.lbf"
                        pos_from { column: 5 row: 28 }
                        pos_to { column: 8 row: 28 }
                      }
                    }
                  }
                }
                fields {
                  ty_ref {
                    foreign_ty_ref {
                      ty_name {
                        name: "A"
                        source_info {
                          file: "good/Test.lbf"
                          pos_from { column: 7 row: 29 }
                          pos_to { column: 8 row: 29 }
                        }
                      }
                      module_name {
                        parts {
                          name: "C"
                          source_info {
                            file: "good/Test.lbf"
                            pos_from { column: 18 row: 11 }
                            pos_to { column: 19 row: 11 }
                          }
                        }
                        source_info {
                          file: "good/Test.lbf"
                          pos_from { column: 18 row: 11 }
                          pos_to { column: 19 row: 11 }
                        }
                      }
                      source_info {
                        file: "good/Test.lbf"
                        pos_from { column: 5 row: 29 }
                        pos_to { column: 8 row: 29 }
                      }
                    }
                  }
                }
                source_info {
                  file: "good/Test.lbf"
                  pos_from { column: 2 row: 23 }
                  pos_to { column: 8 row: 29 }
                }
              }
            }
          }
          source_info {
            file: "good/Test.lbf"
            pos_from { column: 13 row: 22 }
            pos_to { column: 8 row: 29 }
          }
        }
      }
    }
    source_info {
      file: "good/Test.lbf"
      pos_from { column: 1 row: 22 }
      pos_to { column: 8 row: 29 }
    }
  }
  source_info {
    file: "good/Test.lbf"
    pos_from { column: 1 row: 1 }
    pos_to { column: 1 row: 30 }
  }
}
