[package]
name = "lbr-prelude"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
data-encoding = "2.4.0"
num-bigint = "0.4.4"
proptest = "1.3.1"
serde = "1.0.188"
serde_json = { version = "1.0.107", features = ["arbitrary_precision"] }
thiserror = "1.0.49"
lbr-prelude-derive = { path = "../lbr-prelude-derive", optional = true }

[features]
default = ["derive"]
derive = ["dep:lbr-prelude-derive"]
