[package]
name = "lbr-prelude"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
data-encoding = "2.4.0"
num-bigint = { version = "0.4.4", features = ["serde", "rand"] }
proptest = "1.3.1"
serde = "1.0.188"
serde_json = "1.0.107"
